package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type hostOptions struct {
	AllWrites bool // require approval / block for all writes, not only irreversible
	Write     bool // install the config to the host's default path instead of printing
}

// renderHostConfig emits safety config for the given agent host from a classification.
// claude-code -> settings.json deny/ask/allow rules + a PreToolUse hook script that
// re-checks every Bash command and MCP tool call (the permission rules alone are literal
// prefix patterns and can be sidestepped by path-invoking the binary or quote tricks),
// codex -> read-only sandbox config.toml, opencode -> opencode.json permissions.
// binary is threaded through so the same renderer works for any CLI name, not just "lsqueezy".
//
//nolint:unparam // binary is part of the reusable host-renderer API (always "lsqueezy" here).
func renderHostConfig(host, binary string, cls classification, opts hostOptions) (string, error) {
	switch strings.ToLower(host) {
	case "claude-code", "claude":
		return renderClaudeCode(binary, cls, opts)
	case "codex":
		return renderCodex(binary, cls, opts)
	case "opencode":
		return renderOpenCode(binary, cls, opts)
	default:
		return "", fmt.Errorf("unknown host %q (want claude-code|codex|opencode)", host)
	}
}

// bashPattern builds a Claude Code Bash permission pattern for a command path.
func bashPattern(binary, path string) string {
	return fmt.Sprintf("Bash(%s %s:*)", binary, path)
}

// mcpPattern builds the MCP tool name pattern (prefix differs from the binary name).
func mcpPattern(binary, path string) string {
	return fmt.Sprintf("mcp__%s__%s_%s", binary, binary, strings.ReplaceAll(path, " ", "_"))
}

// blockedPaths returns the CLI paths the guard hard-blocks: irreversible always, plus all
// writes under --all-writes. askedPaths returns what merely requires approval.
func blockedPaths(cls classification, opts hostOptions) (blocked, asked []string) {
	blocked = append(blocked, cls.Irreversible...)
	if opts.AllWrites {
		blocked = append(blocked, cls.Write...)
	} else {
		asked = append(asked, cls.Write...)
	}
	sort.Strings(blocked)
	sort.Strings(asked)
	return blocked, asked
}

func renderClaudeCode(binary string, cls classification, opts hostOptions) (string, error) {
	blocked, asked := blockedPaths(cls, opts)

	deny := []string{}
	ask := []string{}
	allow := []string{}

	for _, p := range blocked {
		deny = append(deny, bashPattern(binary, p), mcpPattern(binary, p))
	}
	// Hard-block the raw-api escape hatch for destructive HTTP methods. The method is the
	// first positional arg (`lsqueezy api DELETE /orders/1`), so these are exact prefix
	// patterns that cannot false-match a GET whose URL path contains "delete".
	for _, m := range apiDestructiveMethods {
		deny = append(deny, fmt.Sprintf("Bash(%s api %s:*)", binary, m))
	}
	for _, p := range asked {
		ask = append(ask, bashPattern(binary, p), mcpPattern(binary, p))
	}
	for _, p := range cls.Read {
		allow = append(allow, bashPattern(binary, p), mcpPattern(binary, p))
	}

	// ${CLAUDE_PROJECT_DIR} is the Claude runtime variable; it is NOT expanded at write
	// time — Claude substitutes it when loading the hook.
	hookRef := "${CLAUDE_PROJECT_DIR}/.claude/hooks/" + binary + "-guard.sh"
	hookEntry := func(matcher string) map[string]any {
		return map[string]any{
			"matcher": matcher,
			"hooks":   []any{map[string]any{"type": "command", "command": hookRef}},
		}
	}
	settings := map[string]any{
		"_comment": "Generated by `" + binary + " agent guard --host claude-code` from the live command tree. " +
			"Irreversible verbs are denied; writes require approval; reads are allowed. " +
			"The PreToolUse hook re-checks every Bash command and " + binary + " MCP tool call, " +
			"because permission rules are literal prefix patterns that a path-invoked binary or " +
			"quote obfuscation would sidestep.",
		"permissions": map[string]any{
			"deny":  deny,
			"ask":   ask,
			"allow": allow,
		},
		"hooks": map[string]any{
			// Hook on both Bash and the exact MCP namespace.
			"PreToolUse": []any{hookEntry("Bash"), hookEntry("mcp__" + binary + "__")},
		},
	}
	settingsJSON, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return "", err
	}

	hook := hookScript(binary, blocked)

	if opts.Write {
		root := findProjectRoot()
		var b strings.Builder
		if err := writeGuardFile(&b, filepath.Join(root, ".claude", "hooks", binary+"-guard.sh"), hook, 0o755); err != nil {
			return "", err
		}
		if err := writeGuardFile(&b, filepath.Join(root, ".claude", "settings.json"), string(settingsJSON)+"\n", 0o644); err != nil {
			return "", err
		}
		return b.String(), nil
	}

	var b strings.Builder
	b.WriteString("# Claude Code agent-safety config. The MCP branch of the hook is a hard block\n")
	b.WriteString("# (structured tool names can't be obfuscated); the Bash branch is best-effort —\n")
	b.WriteString("# it defeats quote/backslash tricks and path-invoked binaries but not variable\n")
	b.WriteString("# indirection or shell aliases, so MCP-only operation (or a read-only sandbox)\n")
	b.WriteString("# is the strongest guarantee. The `" + binary + " api` escape hatch is covered for\n")
	b.WriteString("# DELETE/PUT/POST/PATCH at the method position. Regenerate after upgrading.\n")
	fmt.Fprintf(&b, "# ----- .claude/hooks/%s-guard.sh -----\n%s\n", binary, hook)
	fmt.Fprintf(&b, "# ----- .claude/settings.json -----\n%s\n", string(settingsJSON))
	return b.String(), nil
}

// apiDestructiveMethods are the raw-api HTTP methods the guard hard-blocks. PATCH is
// included as it is also write-capable; GET/HEAD stay gated only by the generic `api` ask.
var apiDestructiveMethods = []string{"DELETE", "PUT", "POST", "PATCH"}

// hookScript generates the PreToolUse hook script. Commands are matched by exact
// SUBCOMMAND PATH at the command position, not by bare verbs anywhere in the line, so
// arguments containing a blocked word do not cause false positives (e.g.
// `lsqueezy discounts create --name "refund promo"` is allowed; only
// `lsqueezy orders refund` at the command position is blocked).
func hookScript(binary string, blockedCLI []string) string {
	// Ordered, deduplicated cli-path list for the Bash branch and exact tool-name list
	// for the MCP branch.
	seen := map[string]bool{}
	var cliPaths, toolNames []string
	for _, p := range blockedCLI {
		if !seen[p] {
			seen[p] = true
			cliPaths = append(cliPaths, p)
			toolNames = append(toolNames, mcpPattern(binary, p))
		}
	}

	shellArray := func(name string, items []string) string {
		var b strings.Builder
		b.WriteString(name + "=(\n")
		for _, it := range items {
			// Escape any single quotes (there should be none, but be safe).
			b.WriteString("  '" + strings.ReplaceAll(it, "'", "'\\''") + "'\n")
		}
		b.WriteString(")")
		return b.String()
	}

	return `#!/usr/bin/env bash
# ` + binary + ` agent guard — blocks irreversible ` + binary + ` operations on the Bash and
# MCP surfaces. Generated by ` + "`" + binary + " agent guard`" + `; regenerate after upgrading
# ` + binary + ` so new commands are covered.
#
# MATCHING STRATEGY: commands are matched by exact SUBCOMMAND PATH at the command
# position, not by bare verbs anywhere in the line. This prevents:
#   - false positives: "` + binary + ` discounts create --name 'refund promo'" is NOT
#     blocked because "discounts create" is not in the blocked set.
#   - false negatives: bare-verb grep would miss chained commands after a pipe or
#     semicolon in a multi-command line.
#
# For each blocked cli-path P, we check whether the CLEANED command string matches
# the anchored ERE:
#   (^|[;&|([:space:]]+)([^[:space:]]*/)?` + binary + `[[:space:]]+<P>([[:space:];&|)]|$)
# which ensures ` + binary + `+P appears at a command position. The optional
# ([^[:space:]]*/)? prefix also catches path-invoked binaries like ./bin/` + binary + `
# or /usr/local/bin/` + binary + `.
#
# The MCP branch is an exact set-membership check — no glob or regex.
# The "` + binary + ` api" escape hatch is caught by method-position matching:
#   ` + binary + ` api (DELETE|PUT|POST|PATCH) at word boundary.
#
# De-obfuscation: quotes (\042 / \047) and backslash (\134) are stripped from the raw
# command string before pattern matching to defeat trivial tricks like
#   ` + binary + ` orders re""fund 5
# Variable indirection (a=refund; ` + binary + ` orders $a 5) and aliases are NOT
# defeated — use MCP-only mode or a read-only sandbox for a hard guarantee.

# --- blocked command paths (Bash surface) ---
` + shellArray("blocked_cmds", cliPaths) + `

# --- blocked MCP tool names (exact) ---
` + shellArray("blocked_tools", toolNames) + `

input=$(cat)

# deny_raw emits a denial with a FIXED reason via printf (no jq needed).
deny_raw() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
  exit 0
}

# deobfuscate strips quote chars (\042=", \047=', \134=\) and collapses newlines to a
# single line so obfuscation tricks can't split a token across lines. Applied in BOTH
# the jq and no-jq branches.
deobfuscate() {
  printf '%s' "$1" | tr -d '\042\047\134' | tr '\n' ' '
}

# bash_is_blocked returns 0 (true) if the cleaned command contains a blocked
# ` + binary + ` subcommand at the command position.
bash_is_blocked() {
  local cleaned="$1"
  local p
  for p in "${blocked_cmds[@]}"; do
    # Paths are "word word", so only spaces need mapping to [[:space:]]+.
    local pat
    pat=$(printf '%s' "$p" | sed 's/ /[[:space:]]+/g')
    if printf '%s' "$cleaned" | grep -qiE "(^|[;&|([:space:]]+)([^[:space:]]*/)?` + binary + `[[:space:]]+${pat}([[:space:];&|)]|\$)"; then
      return 0
    fi
  done
  return 1
}

# api_is_blocked returns 0 (true) if the command is a destructive raw-api call.
# Matches ` + binary + ` api (DELETE|PUT|POST|PATCH) at the method position only, so a
# GET whose PATH contains "refund" or "delete" is NOT blocked. Case-insensitive because
# the CLI upcases the method itself (` + "`" + binary + ` api delete /x` + "`" + ` is valid).
api_is_blocked() {
  local cleaned="$1"
  printf '%s' "$cleaned" | grep -qiE "(^|[;&|([:space:]]+)([^[:space:]]*/)?` + binary + `[[:space:]]+api[[:space:]]+(DELETE|PUT|POST|PATCH)[[:space:]/]"
}

# Without jq we cannot isolate the tool_name/command fields. Fail safe: apply the same
# de-obfuscation and anchored path matching on the raw payload rather than a loose
# verb scan that would flag any Bash line mentioning a blocked word.
if ! command -v jq >/dev/null 2>&1; then
  # Flatten JSON punctuation to spaces BEFORE matching: in the raw compact
  # payload the command value is glued to its key ("command":"...) and the
  # anchored pattern could never match — the branch would silently fail OPEN.
  flat=$(printf '%s' "$input" | tr '\n{}:,' '     ')
  cleaned=$(deobfuscate "$flat")
  if bash_is_blocked "$cleaned"; then
    deny_raw "` + binary + ` agent guard: irreversible operation blocked (jq unavailable; raw match)."
  fi
  if api_is_blocked "$cleaned"; then
    deny_raw "` + binary + ` agent guard: destructive raw-api call blocked (jq unavailable; raw match)."
  fi
  exit 0
fi

# deny emits the denial with a jq-escaped reason so an interpolated value can never
# break out of the JSON string.
deny() {
  jq -c -n --arg r "$1" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}

tool=$(printf '%s' "$input" | jq -r '.tool_name // empty')
case "$tool" in
  Bash)
    raw_cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // empty')
    cleaned=$(deobfuscate "$raw_cmd")
    if bash_is_blocked "$cleaned"; then
      deny "` + binary + ` agent guard: irreversible operation blocked."
    fi
    if api_is_blocked "$cleaned"; then
      deny "` + binary + ` agent guard: destructive raw-api call blocked. Use dedicated commands or MCP-only mode."
    fi
    ;;
  *)
    # MCP branch: exact set-membership — no substring or regex match.
    for t in "${blocked_tools[@]}"; do
      if [ "$tool" = "$t" ]; then
        deny "` + binary + ` agent guard: irreversible MCP tool blocked (${tool})."
      fi
    done
    ;;
esac
exit 0
`
}

func renderCodex(binary string, cls classification, opts hostOptions) (string, error) {
	blocked, asked := blockedPaths(cls, opts)

	var b strings.Builder
	b.WriteString("# Codex agent-safety config (~/.codex/config.toml).\n")
	b.WriteString("# IMPORTANT: Codex sandboxes restrict FILESYSTEM and COMMAND EXECUTION, not\n")
	b.WriteString("# network access — a " + binary + " command still reaches the API over the network.\n")
	b.WriteString("# approval_policy=\"untrusted\" pauses for human approval before EVERY shell\n")
	b.WriteString("# command and MCP tool call; it does NOT hard-block destructive operations.\n")
	b.WriteString("# For a hard block use --host claude-code (its PreToolUse hook denies at the\n")
	b.WriteString("# command level).\n")
	b.WriteString("sandbox_mode    = \"read-only\"\n")
	b.WriteString("approval_policy = \"untrusted\"\n\n")
	b.WriteString("# Irreversible commands (never approve without a human double-check):\n")
	for _, p := range blocked {
		fmt.Fprintf(&b, "#   %s %s\n", binary, p)
	}
	if len(asked) > 0 {
		b.WriteString("# Writes (approve case by case):\n")
		for _, p := range asked {
			fmt.Fprintf(&b, "#   %s %s\n", binary, p)
		}
	}
	content := b.String()

	if opts.Write {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("cannot determine home directory for Codex config: %w", err)
		}
		var out strings.Builder
		if err := writeGuardFile(&out, filepath.Join(home, ".codex", "config.toml"), content, 0o644); err != nil {
			return "", err
		}
		return out.String(), nil
	}
	return content, nil
}

func renderOpenCode(binary string, cls classification, opts hostOptions) (string, error) {
	blocked, asked := blockedPaths(cls, opts)

	// Exact per-command rules under permission.bash — no trailing-glob verb patterns
	// ("lsqueezy * refund*" could shadow reads). MCP tool rules sit beside "bash",
	// keyed by tool name.
	bashRules := map[string]any{"*": "allow"}
	perms := map[string]any{}
	toolKey := func(p string) string { return binary + "_" + strings.ReplaceAll(p, " ", "_") }

	for _, p := range cls.Read {
		bashRules[fmt.Sprintf("%s %s", binary, p)] = "allow"
	}
	for _, p := range asked {
		bashRules[fmt.Sprintf("%s %s", binary, p)] = "ask"
		perms[toolKey(p)] = "ask"
	}
	for _, p := range blocked {
		bashRules[fmt.Sprintf("%s %s", binary, p)] = "deny"
		perms[toolKey(p)] = "deny"
	}
	// Block destructive raw-api methods (method is the first positional arg).
	for _, m := range apiDestructiveMethods {
		bashRules[fmt.Sprintf("%s api %s", binary, m)] = "deny"
	}
	perms["bash"] = bashRules

	cfg := map[string]any{
		"$schema":    "https://opencode.ai/config.json",
		"permission": perms,
	}
	b, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return "", err
	}
	content := string(b) + "\n"

	if opts.Write {
		var out strings.Builder
		if err := writeGuardFile(&out, "opencode.json", content, 0o644); err != nil {
			return "", err
		}
		return out.String(), nil
	}
	return content, nil
}

// writeGuardFile writes content to path (creating parent dirs), refusing to overwrite an
// existing file — the user may have merged local edits into a previously generated config.
func writeGuardFile(out *strings.Builder, path, content string, perm os.FileMode) error {
	if _, err := os.Stat(path); err == nil {
		fmt.Fprintf(out, "# %s already exists — review and merge manually:\n%s\n", path, content)
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(content), perm); err != nil { // #nosec G306 -- hook script needs 0o755
		return err
	}
	fmt.Fprintf(out, "wrote %s\n", path)
	return nil
}

// findProjectRoot walks up from the current working directory looking for a .git
// directory, which marks the project root. Falls back to CWD if none is found.
func findProjectRoot() string {
	cwd, err := os.Getwd()
	if err != nil {
		return "."
	}
	dir := cwd
	for {
		if fi, err := os.Stat(filepath.Join(dir, ".git")); err == nil && fi.IsDir() {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return cwd
		}
		dir = parent
	}
}
