package commands

import (
	"encoding/json"
	"fmt"
	"strings"
)

type hostOptions struct {
	AllWrites bool // require approval / block for all writes, not only irreversible
	Write     bool // (reserved) write to host's default path; here we always emit to stdout
}

// renderHostConfig emits safety config for the given agent host from a classification.
// claude-code -> settings.json deny/ask rules (+ a note about the PreToolUse hook),
// codex -> read-only sandbox config.toml, opencode -> opencode.json permissions.
// binary is threaded through so the same renderer works for any CLI name, not just "lsqueezy".
//
//nolint:unparam // binary is part of the reusable host-renderer API (always "lsqueezy" here).
func renderHostConfig(host, binary string, cls classification, opts hostOptions) (string, error) {
	switch strings.ToLower(host) {
	case "claude-code", "claude":
		return renderClaudeCode(binary, cls, opts)
	case "codex":
		return renderCodex(binary, cls, opts)
	case "opencode":
		return renderOpenCode(binary, cls, opts)
	default:
		return "", fmt.Errorf("unknown host %q (want claude-code|codex|opencode)", host)
	}
}

// bashPattern builds a Claude Code Bash permission pattern for a command path.
func bashPattern(binary, path string) string {
	return fmt.Sprintf("Bash(%s %s:*)", binary, path)
}

// mcpPattern builds the MCP tool name pattern (prefix differs from the binary name).
func mcpPattern(binary, path string) string {
	return fmt.Sprintf("mcp__%s__%s_%s", binary, binary, strings.ReplaceAll(path, " ", "_"))
}

func renderClaudeCode(binary string, cls classification, opts hostOptions) (string, error) {
	deny := []string{}
	ask := []string{}
	allow := []string{}

	for _, p := range cls.Irreversible {
		deny = append(deny, bashPattern(binary, p), mcpPattern(binary, p))
	}
	for _, p := range cls.Write {
		if opts.AllWrites {
			deny = append(deny, bashPattern(binary, p), mcpPattern(binary, p))
		} else {
			ask = append(ask, bashPattern(binary, p), mcpPattern(binary, p))
		}
	}
	for _, p := range cls.Read {
		allow = append(allow, bashPattern(binary, p), mcpPattern(binary, p))
	}

	cfg := map[string]any{
		"_comment": "Generated by `lsqueezy agent guard --host claude-code` from the live command tree. " +
			"Irreversible verbs are denied; writes require approval; reads are allowed. " +
			"For defense in depth, also wire a PreToolUse hook that re-checks the Bash command.",
		"permissions": map[string]any{
			"deny":  deny,
			"ask":   ask,
			"allow": allow,
		},
	}
	b, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b) + "\n", nil
}

func renderCodex(binary string, cls classification, opts hostOptions) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by `lsqueezy agent guard --host codex` from the live command tree.\n")
	b.WriteString("# A read-only sandbox: writes/deletes are not auto-approved.\n")
	b.WriteString("[sandbox]\n")
	b.WriteString("mode = \"read-only\"\n\n")
	writeLabel := "# Writes (require approval):\n"
	if opts.AllWrites {
		writeLabel = "# Writes (blocked: --all-writes):\n"
	}
	b.WriteString("# Irreversible commands (never auto-run):\n")
	for _, p := range cls.Irreversible {
		fmt.Fprintf(&b, "#   %s %s\n", binary, p)
	}
	b.WriteString(writeLabel)
	for _, p := range cls.Write {
		fmt.Fprintf(&b, "#   %s %s\n", binary, p)
	}
	return b.String(), nil
}

func renderOpenCode(binary string, cls classification, opts hostOptions) (string, error) {
	perms := map[string]string{}
	for _, p := range cls.Read {
		perms[fmt.Sprintf("%s %s", binary, p)] = "allow"
	}
	for _, p := range cls.Write {
		v := "ask"
		if opts.AllWrites {
			v = "deny"
		}
		perms[fmt.Sprintf("%s %s", binary, p)] = v
	}
	for _, p := range cls.Irreversible {
		perms[fmt.Sprintf("%s %s", binary, p)] = "deny"
	}
	cfg := map[string]any{
		"$schema":     "https://opencode.ai/config.json",
		"_comment":    "Generated by `lsqueezy agent guard --host opencode` from the live command tree.",
		"permissions": perms,
	}
	b, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b) + "\n", nil
}
